### Crear un nuevo material
POST http://localhost:8000/materials/
Content-Type: application/json

{
  "NOMBRE": "Cemento",
  "DESCRIPCION": "Saco de cemento de alta calidad",
  "CANTIDAD": 50,
  "PRECIO_UNITARIO": 300,
  "CANTIDAD_MINIMA": 5
}

### Obtener el listado de todos los materiales
GET http://localhost:8000/materials/
#Authorization: Bearer {{access_token}}

### Obtener un material por ID
GET http://localhost:8000/materials/2
#Authorization: Bearer {{access_token}}

### Actualizar un material existente por ID
PUT http://localhost:8000/materials/2
Content-Type: application/json
#Authorization: Bearer {{access_token}}

{
  "NOMBRE": "Cemento Actualizado",
  "DESCRIPCION": "Saco de cemento de alta calidad actualizado",
  "CANTIDAD": 75,
  "PRECIO_UNITARIO": 350,
  "PROVEEDOR_ID": 1,
  "CANTIDAD_MINIMA": 10
}

### Eliminar un material por ID
DELETE http://localhost:8000/materials/2
#Authorization: Bearer {{access_token}}
