POST http://localhost:8000/tool-allocations/
Content-Type: application/json

{
  "tool_allocation_data": {
  "CANTIDAD": 15,
  "FLUJO_HERRAMIENTA_ID": 1,
  "PROYECTO_ID": 1
},
  "flow_tool_data": {
  "CANTIDAD": 15,
  "MOVIMIENTO": "salida",
  "FECHA": "2024-01-01",
  "ALMACEN_ID": 1,
  "HERRAMIENTA_ID": 1
}
}

### Llamar a todos los flujos de herramienta
GET http://localhost:8000/tool-allocations/
#Authorization: Bearer {{access_token}}

### Obtener un flujo de herramienta por ID
GET http://localhost:8000/tool-allocations/1
#Authorization: Bearer {{access_token}}

### Actualizar un flujo de herramienta existente por ID
PUT http://localhost:8000/tool-allocations/3
Content-Type: application/json
#Authorization: Bearer {{access_token}}

{
  "CANTIDAD": 25,
  "FLUJO_HERRAMIENTA_ID": 1,
  "PROYECTO_ID": 1
}

### Eliminar un flujo de herramienta por ID
DELETE http://localhost:8000/tool-allocations/1
#Authorization: Bearer {{access_token}}
